window.MODEL_META = {
  // Defaults sized for an early-stage / Series-A startup (~25 employees,
  // dev-heavy headcount). Sources: Carta State of Private Markets (median
  // seed: 8-12 FTE, Series A: 20-50 FTE), Crunchbase company-size data.
  defaultSizing: {
    developers:    15,
    endpoints:     40,
    users:         30,
    cloudInstances: 20,
    containers:    15,
  },

  costModelDimensions: {
    'per-developer': 'developers',
    'per-committer': 'developers',
    'per-endpoint':  'endpoints',
    'per-device':    'endpoints',
    'per-asset':     'endpoints',
    'per-user':      'users',
    'per-instance':  'cloudInstances',
    'per-scanner':   null,
    'fixed':         null,
    'consumption':   null,
    'free':          null,
  },

  ecosystems: {
    'aws-native':       { label: 'AWS-native',       color: '#ff9900' },
    'azure-native':     { label: 'Azure-native',     color: '#2563c8' },
    'gcp-native':       { label: 'GCP-native',       color: '#4285f4' },
    'open-source':      { label: 'Open source',      color: '#2a8d5e' },
    'commercial':       { label: 'Commercial',       color: '#7a3fa8' },
    'kubernetes-native':{ label: 'Kubernetes-native',color: '#326ce5' },
  },
};

const SOC2_DOC = 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2';
const CSF2_DOC = 'https://www.nist.gov/cyberframework/csf-2-0';
const SSDF_DOC = 'https://csrc.nist.gov/pubs/sp/800/218/final';

window.CONTROLS = [
  // ----- SOC 2 Trust Services Criteria -----
  { id: 'soc2.cc4.1', framework: 'SOC 2', code: 'CC4.1',
    title: 'Ongoing evaluation of control effectiveness',
    capabilities: ['vm-endpoint','vm-cloud','reporting','siem'],
    docUrl: SOC2_DOC },
  { id: 'soc2.cc6.1', framework: 'SOC 2', code: 'CC6.1',
    title: 'Logical access controls',
    capabilities: ['iam','secrets-mgmt'],
    docUrl: SOC2_DOC },
  { id: 'soc2.cc6.6', framework: 'SOC 2', code: 'CC6.6',
    title: 'Boundary protection (network / identity perimeter)',
    capabilities: ['waf','service-mesh','iam'],
    docUrl: SOC2_DOC },
  { id: 'soc2.cc7.1', framework: 'SOC 2', code: 'CC7.1',
    title: 'Detect configuration changes that introduce vulnerabilities',
    capabilities: ['vm-endpoint','vm-cloud','container-scan','cspm','iac-scan'],
    docUrl: SOC2_DOC },
  { id: 'soc2.cc7.2', framework: 'SOC 2', code: 'CC7.2',
    title: 'Monitor system components for vulnerabilities',
    capabilities: ['vm-endpoint','vm-cloud','container-scan','sast','dast','sca','cspm'],
    docUrl: SOC2_DOC },
  { id: 'soc2.cc7.3', framework: 'SOC 2', code: 'CC7.3',
    title: 'Detect security incidents',
    capabilities: ['edr','siem','runtime-detect','vm-cloud'],
    docUrl: SOC2_DOC },
  { id: 'soc2.cc7.4', framework: 'SOC 2', code: 'CC7.4',
    title: 'Respond to identified incidents',
    capabilities: ['edr','siem','runtime-detect'],
    docUrl: SOC2_DOC },

  // ----- NIST CSF 2.0 -----
  { id: 'csf.id.ra-01', framework: 'NIST CSF 2.0', code: 'ID.RA-01',
    title: 'Vulnerabilities in assets identified, validated, recorded',
    capabilities: ['vm-endpoint','vm-cloud','container-scan','sast','dast','sca'],
    docUrl: CSF2_DOC },
  { id: 'csf.id.ra-08', framework: 'NIST CSF 2.0', code: 'ID.RA-08',
    title: 'Processes for receiving, analyzing, responding to vuln disclosures',
    capabilities: ['vm-endpoint','reporting','pentest'],
    docUrl: CSF2_DOC },
  { id: 'csf.de.cm-01', framework: 'NIST CSF 2.0', code: 'DE.CM-01',
    title: 'Networks and network services monitored',
    capabilities: ['siem','runtime-detect','waf'],
    docUrl: CSF2_DOC },
  { id: 'csf.de.cm-08', framework: 'NIST CSF 2.0', code: 'DE.CM-08',
    title: 'Vulnerability scans performed',
    capabilities: ['vm-endpoint','vm-cloud','container-scan'],
    docUrl: CSF2_DOC },
  { id: 'csf.de.cm-09', framework: 'NIST CSF 2.0', code: 'DE.CM-09',
    title: 'Computing hardware/software, runtime environments, data monitored',
    capabilities: ['edr','vm-endpoint','runtime-detect'],
    docUrl: CSF2_DOC },
  { id: 'csf.pr.ps-02', framework: 'NIST CSF 2.0', code: 'PR.PS-02',
    title: 'Software maintained, replaced, removed (patch mgmt)',
    capabilities: ['patch-mgmt'],
    docUrl: CSF2_DOC },
  { id: 'csf.pr.aa-05', framework: 'NIST CSF 2.0', code: 'PR.AA-05',
    title: 'Access permissions / authorizations managed',
    capabilities: ['iam'],
    docUrl: CSF2_DOC },
  { id: 'csf.pr.ds-02', framework: 'NIST CSF 2.0', code: 'PR.DS-02',
    title: 'Data-in-transit protected',
    capabilities: ['service-mesh','waf'],
    docUrl: CSF2_DOC },

  // ----- NIST SSDF (SP 800-218) -----
  { id: 'ssdf.po.5', framework: 'NIST SSDF', code: 'PO.5',
    title: 'Implement and maintain secure environments for software development',
    capabilities: ['code-review-controls','pipeline-security','secrets-mgmt'],
    docUrl: SSDF_DOC },
  { id: 'ssdf.ps.1', framework: 'NIST SSDF', code: 'PS.1',
    title: 'Protect all forms of code from unauthorized access and tampering',
    capabilities: ['code-review-controls','precommit-hooks','sbom'],
    docUrl: SSDF_DOC },
  { id: 'ssdf.ps.3', framework: 'NIST SSDF', code: 'PS.3',
    title: 'Provide a mechanism for verifying software release integrity',
    capabilities: ['sbom','policy-as-code'],
    docUrl: SSDF_DOC },
  { id: 'ssdf.pw.7', framework: 'NIST SSDF', code: 'PW.7',
    title: 'Review and analyze code for vulnerabilities',
    capabilities: ['sast','sca','code-review-controls'],
    docUrl: SSDF_DOC },
  { id: 'ssdf.pw.8', framework: 'NIST SSDF', code: 'PW.8',
    title: 'Test executable code for vulnerabilities',
    capabilities: ['dast','container-scan','iac-scan'],
    docUrl: SSDF_DOC },
  { id: 'ssdf.rv.1', framework: 'NIST SSDF', code: 'RV.1',
    title: 'Identify and confirm vulnerabilities on an ongoing basis',
    capabilities: ['vm-endpoint','vm-cloud','sca','reporting'],
    docUrl: SSDF_DOC },
];

window.CAPABILITIES = [
  // ----- Plan & Code -----
  { id: 'code-review-controls', name: 'Code Review & CODEOWNERS',
    domain: 'Plan & Code', scope: 'fixed',
    description: 'CODEOWNERS + branch protection on high-risk modules. Process control on the source-control platform.' },
  { id: 'precommit-hooks', name: 'Pre-Commit Hooks (secrets, lint)',
    domain: 'Plan & Code', scope: 'fixed',
    description: 'Local hooks that catch secrets, linter violations, and obvious vulns before code is committed.' },
  { id: 'sast', name: 'Static Application Security Testing',
    domain: 'Plan & Code', scope: 'developers',
    description: 'Static analysis of in-house source code in IDE and CI.' },

  // ----- Build & Package -----
  { id: 'sca', name: 'Software Composition Analysis',
    domain: 'Build & Package', scope: 'developers',
    description: 'Vulnerability + license analysis of open-source dependencies.' },
  { id: 'sbom', name: 'SBOM Generation & Signing',
    domain: 'Build & Package', scope: 'fixed',
    description: 'Generate Software Bill of Materials per release in CycloneDX/SPDX format, sign artifacts and emit build provenance/attestations.' },
  { id: 'container-scan', name: 'Container / Image Scanning',
    domain: 'Build & Package', scope: 'containers',
    description: 'CVE + misconfig scanning of container images in registry and at runtime.' },
  { id: 'iac-scan', name: 'Infrastructure-as-Code Scanning',
    domain: 'Build & Package', scope: 'fixed',
    description: 'Scan Terraform / CloudFormation / Kubernetes manifests for misconfig before apply.' },
  { id: 'pipeline-security', name: 'Pipeline / CI Hardening',
    domain: 'Build & Package', scope: 'fixed',
    description: 'Lock down CI runners, credentials, agent privilege, and who can edit pipeline definitions. Pipeline as code.' },

  // ----- Test & Deploy -----
  { id: 'dast', name: 'Dynamic Application Security Testing',
    domain: 'Test & Deploy', scope: 'fixed',
    description: 'Runtime web/API scanning against staging or production-like environments.' },
  { id: 'policy-as-code', name: 'Policy-as-Code / Admission Control',
    domain: 'Test & Deploy', scope: 'fixed',
    description: 'Codified guardrails enforced at deploy and runtime: admission controllers, automated remediation of misconfig, drift correction.' },
  { id: 'secrets-mgmt', name: 'Secrets Management',
    domain: 'Test & Deploy', scope: 'fixed',
    description: 'Vault / Secrets Manager for runtime credentials. No hard-coded secrets.' },
  { id: 'pentest', name: 'Penetration Testing (Annual)',
    domain: 'Test & Deploy', scope: 'fixed',
    description: 'Annual external pentest covering the application + supporting infrastructure.' },

  // ----- Asset Vulnerability -----
  { id: 'vm-endpoint', name: 'Endpoint Vulnerability Scanning',
    domain: 'Asset Vulnerability', scope: 'endpoints',
    description: 'Authenticated/unauthenticated scanning of workstations + servers.' },
  { id: 'vm-cloud', name: 'Cloud Workload Vulnerability Scanning',
    domain: 'Asset Vulnerability', scope: 'cloud',
    description: 'Vuln visibility across AWS / Azure / GCP cloud instances + services.' },
  { id: 'patch-mgmt', name: 'Patch Management',
    domain: 'Asset Vulnerability', scope: 'endpoints',
    description: 'Deploys remediations identified by VM. MDM/UEM-driven on workstations, automation-driven on cloud.' },
  { id: 'reporting', name: 'VM Reporting & Audit Evidence',
    domain: 'Asset Vulnerability', scope: 'fixed',
    description: 'Dashboards + exports for SOC 2 evidence and exec reporting.' },

  // ----- Detect & Respond -----
  { id: 'edr', name: 'Endpoint Detection & Response',
    domain: 'Detect & Respond', scope: 'endpoints',
    description: 'Behavioral detection on workstations and servers.' },
  { id: 'siem', name: 'SIEM / Log Aggregation',
    domain: 'Detect & Respond', scope: 'fixed',
    description: 'Centralized log + alert. Correlates across cloud, endpoint, identity.' },
  { id: 'runtime-detect', name: 'Runtime Threat Detection',
    domain: 'Detect & Respond', scope: 'fixed',
    description: 'Syscall / eBPF-based runtime detection of anomalous behavior in containers and hosts (Falco-class).' },
  { id: 'cspm', name: 'Cloud Security Posture Management',
    domain: 'Detect & Respond', scope: 'cloud',
    description: 'Misconfig + compliance scanning for AWS / Azure / GCP.' },
  { id: 'cnapp', name: 'Cloud-Native App Protection (CWPP+CSPM)',
    domain: 'Detect & Respond', scope: 'cloud',
    description: 'Combined workload + posture protection in one console.' },
  { id: 'waf', name: 'Web Application Firewall',
    domain: 'Detect & Respond', scope: 'fixed',
    description: 'Edge filtering of web/API traffic with managed rule sets and rate limiting.' },

  // ----- Data & Identity -----
  { id: 'iam', name: 'Identity & Access Management',
    domain: 'Data & Identity', scope: 'users',
    description: 'Workforce + workload identity, SSO, MFA, conditional access.' },
  { id: 'service-mesh', name: 'Service Mesh / Zero-Trust Networking',
    domain: 'Data & Identity', scope: 'fixed',
    description: 'Service-to-service mTLS, identity-aware traffic policy, segmentation.' },
  { id: 'email-sec', name: 'Email Security',
    domain: 'Data & Identity', scope: 'users',
    description: 'Anti-phish / BEC / malware. Layered on top of mailbox provider native filtering.' },
  { id: 'dlp', name: 'CASB / DLP',
    domain: 'Data & Identity', scope: 'users',
    description: 'Data-loss prevention across SaaS apps and managed devices.' },
];

window.ECOSYSTEM_LANES = [
  { id: 'plan-code', name: 'Plan & Code',
    tagline: 'Code review, pre-commit, SAST',
    capabilities: ['code-review-controls', 'precommit-hooks', 'sast'] },
  { id: 'build', name: 'Build & Package',
    tagline: 'SCA, SBOM, container, IaC, pipeline',
    capabilities: ['sca', 'sbom', 'container-scan', 'iac-scan', 'pipeline-security'] },
  { id: 'test-deploy', name: 'Test & Deploy',
    tagline: 'DAST, policy-as-code, secrets, pentest',
    capabilities: ['dast', 'policy-as-code', 'secrets-mgmt', 'pentest'] },
  { id: 'asset-vuln', name: 'Asset Vulnerability',
    tagline: 'Endpoint, cloud, patch, evidence',
    capabilities: ['vm-endpoint', 'vm-cloud', 'patch-mgmt', 'reporting'] },
  { id: 'detect-respond', name: 'Detect & Respond',
    tagline: 'EDR, SIEM, runtime, posture, WAF',
    capabilities: ['edr', 'siem', 'runtime-detect', 'cspm', 'cnapp', 'waf'] },
  { id: 'data-identity', name: 'Data & Identity',
    tagline: 'IAM, mesh, email, DLP',
    capabilities: ['iam', 'service-mesh', 'email-sec', 'dlp'] },
];

window.DSO_STAGES = [
  { id: 'plan',       name: 'Plan',       tagline: 'Threat model · code review',
    capabilities: ['code-review-controls'] },
  { id: 'pre-commit', name: 'Pre-Commit', tagline: 'Local hooks · secrets',
    capabilities: ['precommit-hooks'] },
  { id: 'build',      name: 'Build',      tagline: 'SAST · SCA · SBOM · IaC · container · pipeline',
    capabilities: ['sast','sca','sbom','container-scan','iac-scan','pipeline-security'] },
  { id: 'test',       name: 'Test',       tagline: 'DAST against staging',
    capabilities: ['dast'] },
  { id: 'deploy',     name: 'Deploy',     tagline: 'Secrets · admission policy',
    capabilities: ['secrets-mgmt','policy-as-code'] },
  { id: 'operate',    name: 'Operate',    tagline: 'EDR · runtime · WAF · SIEM · posture',
    capabilities: ['vm-cloud','vm-endpoint','edr','runtime-detect','cspm','cnapp','waf','siem'] },
];

window.ENFORCEMENT_PHASES = [
  { id: 'none',       label: 'Not yet',     order: 0, color: '#cccccc',
    description: 'Capability not in pipeline yet.' },
  { id: 'visibility', label: 'P1 Visibility', order: 1, color: '#2563c8',
    description: 'Tools run in report-only mode. No blocking. Build the baseline.' },
  { id: 'soft',       label: 'P2 Soft enforcement', order: 2, color: '#b06a16',
    description: 'Critical findings flag the PR; manual override allowed. Trains urgency.' },
  { id: 'hard',       label: 'P3 Hard enforcement', order: 3, color: '#2a8d5e',
    description: 'Pipeline blocks on critical findings. SBOM mandatory per release.' },
];

window.DSO_QUICK_WINS = [
  { id: 'high-risk-codeowners', title: 'High-risk code CODEOWNERS', stage: 'plan',     capability: 'code-review-controls' },
  { id: 'sbom-deps',            title: 'SBOM + dependency auto-PRs', stage: 'commit',   capability: 'sbom' },
  { id: 'self-service-scan',    title: 'Developer self-service scanning', stage: 'pre-commit', capability: 'sast' },
  { id: 'security-in-backlog',  title: 'Auto-create tickets from findings', stage: 'commit', capability: 'sast' },
  { id: 'iac-conversion',       title: 'Eliminate snowflake configs (IaC)', stage: 'deploy', capability: 'iac-scan' },
  { id: 'pipeline-hardening',   title: 'Harden the pipeline itself',  stage: 'build',  capability: 'pipeline-security' },
  { id: 'security-smoke',       title: 'Automated security smoke tests', stage: 'test', capability: 'dast' },
  { id: 'container-baseline',   title: 'Trusted base images + non-root', stage: 'build', capability: 'container-scan' },
];

window.CALMS = [
  { letter: 'C', name: 'Culture',     summary: 'Blameless, shared ownership across Dev/QA/Ops/Sec.' },
  { letter: 'A', name: 'Automation',  summary: 'Everything-as-code, version-controlled, repeatable.' },
  { letter: 'L', name: 'Lean',        summary: 'Lightweight checks, fast feedback. Remove low-value checks.' },
  { letter: 'M', name: 'Measurement', summary: 'Track findings/fix-time/false-positives + DORA metrics.' },
  { letter: 'S', name: 'Sharing',     summary: 'Open dashboards, security in retros + lunch-and-learns.' },
];

window.SOLUTIONS = [
    { id: 'none', vendor: '(none)', name: 'Not selected',
    capabilities: [],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: '', contact: '',
            note: 'No tool chosen for this capability. The Coverage matrix will flag any controls that depend on it.' },
    ecosystem: [], gap: true,
    notes: 'Default for every capability. Pick a real tool to cover it.' },

    { id: 'codeowners-native', vendor: 'Source-control native', name: 'CODEOWNERS + branch / merge protection',
    capabilities: ['code-review-controls'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners',
            contact: 'DevOps lead',
            note: 'Vendor-neutral process control. Implemented natively by every major code host: GitHub, GitLab, Bitbucket, Gitea, Gerrit. No incremental cost on any of them.' },
    extraSources: [
      { label: 'GitHub: About code owners', url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners' },
      { label: 'GitLab: Code Owners', url: 'https://docs.gitlab.com/user/project/codeowners/' },
      { label: 'Bitbucket Cloud: Set up and use code owners', url: 'https://support.atlassian.com/bitbucket-cloud/docs/set-up-and-use-code-owners/' },
      { label: 'Gitea: CODEOWNERS', url: 'https://docs.gitea.com/usage/code-owners' },
    ],
    ecosystem: ['open-source'], dsoStages: ['plan','pre-commit'] },

  { id: 'pre-commit-framework', vendor: 'pre-commit.com', name: 'pre-commit + gitleaks/trufflehog',
    capabilities: ['precommit-hooks'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://pre-commit.com/',
            contact: 'DevOps lead',
            note: 'OSS hook framework. Pair with gitleaks or trufflehog for secret scanning, plus standard linters.' },
    ecosystem: ['open-source'], dsoStages: ['pre-commit'] },

  { id: 'gitleaks', vendor: 'Gitleaks', name: 'Gitleaks (CI mode)',
    capabilities: ['precommit-hooks'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/gitleaks/gitleaks',
            contact: 'AppSec lead',
            note: 'OSS secret scanner, runs in CI or as a pre-commit hook.' },
    ecosystem: ['open-source'], dsoStages: ['pre-commit','commit'],
    ci: { github: { stage: 'static',
      step: { name: 'Gitleaks', uses: 'gitleaks/gitleaks-action@v2', env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' } } } } },

  { id: 'trufflehog', vendor: 'Truffle Security', name: 'TruffleHog (OSS)',
    capabilities: ['precommit-hooks'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/trufflesecurity/trufflehog',
            contact: 'AppSec lead',
            note: 'OSS secret scanner with verifiable detectors. Commercial enterprise tier exists.' },
    ecosystem: ['open-source'], dsoStages: ['pre-commit','commit'],
    ci: { github: { stage: 'static',
      step: { name: 'TruffleHog', uses: 'trufflesecurity/trufflehog@main',
              with: { path: './', base: '${{ github.event.repository.default_branch }}', head: 'HEAD' } } } } },

  { id: 'gitguardian', vendor: 'GitGuardian', name: 'GitGuardian (Business)',
    capabilities: ['precommit-hooks'],
    cost: { model: 'per-developer', unit: 444, units: 100, annual: 44400, source: 'estimate',
            sourceUrl: 'https://www.gitguardian.com/pricing',
            contact: 'Vendor sales',
            note: 'Business tier near $37/dev/month. Real-time secret detection across version control + CI.' },
    ecosystem: ['commercial'], dsoStages: ['pre-commit','commit'],
    ci: { github: { stage: 'static',
      step: { name: 'GitGuardian ggshield', uses: 'GitGuardian/ggshield-action@v1',
              env: { GITGUARDIAN_API_KEY: '${{ secrets.GITGUARDIAN_API_KEY }}',
                     GITHUB_PUSH_BEFORE_SHA: '${{ github.event.before }}',
                     GITHUB_PUSH_BASE_SHA: '${{ github.event.base }}',
                     GITHUB_PULL_BASE_SHA: '${{ github.event.pull_request.base.sha }}',
                     GITHUB_DEFAULT_BRANCH: '${{ github.event.repository.default_branch }}' } } } } },

  { id: 'sonarqube-community', vendor: 'SonarSource', name: 'SonarQube Community',
    capabilities: ['sast'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.sonarsource.com/products/sonarqube/downloads/',
            contact: 'AppSec lead',
            note: 'OSS code-quality + SAST. Self-hosted.' },
    ecosystem: ['open-source'], dsoStages: ['commit','build','pre-release'] },

  { id: 'sonarqube-developer', vendor: 'SonarSource', name: 'SonarQube Developer',
    capabilities: ['sast'],
    cost: { model: 'fixed', unit: 750, units: 1, annual: 750, source: 'estimate',
            sourceUrl: 'https://www.sonarsource.com/plans-and-pricing/sonarqube/',
            contact: 'Vendor sales',
            note: 'Developer Edition starts at $750/yr (per instance, per year, priced by LOC band). Adds branch analysis, security rules.' },
    ecosystem: ['commercial'], dsoStages: ['commit','build','pre-release'] },

  { id: 'semgrep-oss', vendor: 'Semgrep', name: 'Semgrep OSS',
    capabilities: ['sast','precommit-hooks'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/semgrep/semgrep',
            contact: 'AppSec lead',
            note: 'OSS lightweight static analysis with YAML-based custom rules.' },
    ecosystem: ['open-source'], dsoStages: ['pre-commit','commit','build'],
    ci: { github: { stage: 'static',
      step: { name: 'Semgrep', uses: 'semgrep/semgrep-action@v1',
              with: { config: 'p/ci' } } } } },

  { id: 'semgrep-team', vendor: 'Semgrep', name: 'Semgrep AppSec Platform (Team)',
    capabilities: ['sast','precommit-hooks'],
    cost: { model: 'per-developer', unit: 360, units: 100, annual: 36000, source: 'estimate',
            sourceUrl: 'https://semgrep.dev/pricing',
            contact: 'Vendor sales',
            note: 'Team tier near $30/dev/month. Adds managed rules + dashboards.' },
    ecosystem: ['commercial'], dsoStages: ['pre-commit','commit','build'] },

  { id: 'snyk-code', vendor: 'Snyk', name: 'Snyk Code (SAST)',
    capabilities: ['sast'],
    cost: { model: 'per-developer', unit: 300, units: 100, annual: 30000, source: 'estimate',
            sourceUrl: 'https://snyk.io/plans/',
            contact: 'Vendor sales',
            note: 'Team plan near $25/dev/month annualized to $300/dev/year for Code module.' },
    ecosystem: ['commercial'], dsoStages: ['pre-commit','commit','build'],
    ci: { github: { stage: 'static',
      step: { name: 'Snyk Code', uses: 'snyk/actions/node@master',
              env: { SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}' },
              with: { command: 'code test' } } } } },

  { id: 'github-advanced-security', vendor: 'GitHub', name: 'GitHub Advanced Security',
    capabilities: ['sast','sca','sbom','precommit-hooks'],
    cost: { model: 'per-developer', unit: 228, units: 100, annual: 22800, source: 'estimate',
            sourceUrl: 'https://github.com/enterprise/advanced-security',
            contact: 'Vendor sales',
            note: 'List near $19/active-committer/month. CodeQL + secret scanning + Dependabot bundled.' },
    ecosystem: ['commercial'], dsoStages: ['pre-commit','commit','build'] },

  { id: 'gitlab-ultimate', vendor: 'GitLab', name: 'GitLab Ultimate',
    capabilities: ['sast','sca','sbom','dast','container-scan','iac-scan','pipeline-security'],
    cost: { model: 'per-user', unit: 1428, units: 100, annual: 142800, source: 'estimate',
            sourceUrl: 'https://about.gitlab.com/pricing/',
            contact: 'Vendor sales',
            note: 'Ultimate near $119/user/month. Bundles full security suite.' },
    ecosystem: ['commercial'], dsoStages: ['commit','build','test','pre-release'] },

  { id: 'checkmarx-one', vendor: 'Checkmarx', name: 'Checkmarx One',
    capabilities: ['sast','sca','iac-scan','container-scan'],
    cost: { model: 'fixed', unit: 56415, units: 1, annual: 56415, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/checkmarx',
            contact: 'Vendor sales',
            note: 'Checkmarx does not publish list pricing. Vendr aggregates the median annual contract at $56,415. 250-dev enterprise deployments reportedly exceed $500k. Bundle discounts of 20–40% common when buying SAST + SCA + container together.' },
    ecosystem: ['commercial'], dsoStages: ['commit','build','pre-release'] },

  { id: 'bandit', vendor: 'PyCQA', name: 'Bandit (Python)',
    capabilities: ['sast'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://bandit.readthedocs.io/',
            contact: 'AppSec lead',
            note: 'OSS Python static analyzer. Pair with language-specific tools for polyglot codebases.' },
    ecosystem: ['open-source'], dsoStages: ['commit','build'],
    ci: { github: { stage: 'static',
      step: { name: 'Bandit', run: 'pipx run bandit -r .' } } } },

    { id: 'dependabot', vendor: 'GitHub', name: 'Dependabot',
    capabilities: ['sca'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://docs.github.com/en/code-security/dependabot',
            contact: 'DevOps lead',
            note: 'Free with GitHub. Auto-PRs for vulnerable dependencies.' },
    ecosystem: ['open-source'], dsoStages: ['commit'] },

  { id: 'renovate', vendor: 'Mend', name: 'Renovate (OSS)',
    capabilities: ['sca'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/renovatebot/renovate',
            contact: 'DevOps lead',
            note: 'OSS dependency-update bot. More configurable than Dependabot, supports more ecosystems.' },
    ecosystem: ['open-source'], dsoStages: ['commit'] },

  { id: 'owasp-dep-check', vendor: 'OWASP', name: 'OWASP Dependency-Check',
    capabilities: ['sca'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://owasp.org/www-project-dependency-check/',
            contact: 'AppSec lead',
            note: 'OSS CVE scanner for Java, .NET, Ruby, Node, Python, Go.' },
    ecosystem: ['open-source'], dsoStages: ['commit','build'],
    ci: { github: { stage: 'static',
      step: { name: 'OWASP Dependency-Check', uses: 'dependency-check/Dependency-Check_Action@main',
              with: { project: 'sbom', path: '.', format: 'HTML' } } } } },

  { id: 'snyk-open-source', vendor: 'Snyk', name: 'Snyk Open Source (SCA)',
    capabilities: ['sca','sbom'],
    cost: { model: 'per-developer', unit: 300, units: 100, annual: 30000, source: 'estimate',
            sourceUrl: 'https://snyk.io/plans/',
            contact: 'Vendor sales',
            note: 'Team plan near $25/dev/month annualized to $300/dev/year for Open Source module.' },
    ecosystem: ['commercial'], dsoStages: ['pre-commit','commit','build'] },

  { id: 'mend-sca', vendor: 'Mend', name: 'Mend SCA',
    capabilities: ['sca','sbom'],
    cost: { model: 'per-developer', unit: 250, units: 100, annual: 25000, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/mend',
            contact: 'Vendor sales',
            note: 'Mend does not publish list pricing. Vendr / appsecsanta aggregates: per-developer pricing $150–$400/yr; teams of 50–150 devs negotiate to $150–$250/dev/yr after multi-year + bundle discounts. Single subscription covers SCA + SAST + container.' },
    ecosystem: ['commercial'], dsoStages: ['commit','build','pre-release'] },

  { id: 'syft', vendor: 'Anchore', name: 'Syft (CycloneDX/SPDX)',
    capabilities: ['sbom'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/anchore/syft',
            contact: 'AppSec lead',
            note: 'OSS SBOM generation in CycloneDX or SPDX format.' },
    ecosystem: ['open-source'], dsoStages: ['build','pre-release','deploy'],
    ci: { github: { stage: 'build',
      step: { name: 'Syft SBOM', uses: 'anchore/sbom-action@v0',
              with: { format: 'cyclonedx-json', 'output-file': 'sbom.cdx.json' } } } } },

  { id: 'cosign-sigstore', vendor: 'Sigstore', name: 'Cosign + Sigstore',
    capabilities: ['sbom','policy-as-code'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.sigstore.dev/',
            contact: 'AppSec lead',
            note: 'OSS. Sign artifacts and emit in-toto attestations / SLSA provenance.' },
    ecosystem: ['open-source'], dsoStages: ['build','pre-release','deploy'],
    ci: { github: { stage: 'build',
      step: { name: 'Install Cosign', uses: 'sigstore/cosign-installer@v3' } } } },

  { id: 'trivy', vendor: 'Aqua', name: 'Trivy (OSS)',
    capabilities: ['container-scan','iac-scan'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://trivy.dev/',
            contact: 'AppSec lead',
            note: 'OSS image + IaC scanner. Aqua positions Trivy as all-in-one (also does SBOM, SCA), but for SBOM use Syft and for SCA use Snyk OS / Dependabot / OWASP Dep-Check.' },
    ecosystem: ['open-source'], dsoStages: ['commit','build','pre-release'],
    ci: { github: { stage: 'build',
      step: { name: 'Trivy filesystem scan', uses: 'aquasecurity/trivy-action@0.30.0',
              with: { 'scan-type': 'fs', 'scan-ref': '.', 'severity': 'CRITICAL,HIGH' } } } } },

  { id: 'grype', vendor: 'Anchore', name: 'Grype (OSS)',
    capabilities: ['container-scan'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/anchore/grype',
            contact: 'AppSec lead',
            note: 'OSS image + filesystem CVE matcher. Consumes Syft SBOMs. Not an SCA tool, for dependency-graph analysis use Snyk OS, Dependabot, or OWASP Dep-Check.' },
    ecosystem: ['open-source'], dsoStages: ['build','pre-release'],
    ci: { github: { stage: 'build',
      step: { name: 'Grype scan', uses: 'anchore/scan-action@v3',
              with: { path: '.', 'fail-build': 'false' } } } } },

  { id: 'aqua-platform', vendor: 'Aqua Security', name: 'Aqua Cloud Native Security',
    capabilities: ['container-scan','runtime-detect','cnapp'],
    cost: { model: 'fixed', unit: 36325, units: 1, annual: 36325, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/aquasec',
            contact: 'Vendor sales',
            note: 'Aqua does not publish list pricing. Vendr median negotiated contract $36,325/yr (range $32,040–$335,948). TrustRadius lists 3 plans starting at $10,188/yr; SMB CNAPP deployments typically fall in the $30k–$60k bundle range.' },
    ecosystem: ['commercial'], dsoStages: ['build','pre-release','operate'] },

  { id: 'sysdig-secure', vendor: 'Sysdig', name: 'Sysdig Secure',
    capabilities: ['container-scan','runtime-detect','cnapp','cspm'],
    cost: { model: 'fixed', unit: 98145, units: 1, annual: 98145, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/sysdig',
            contact: 'Vendor sales',
            note: 'Sysdig is per-host/per-month. Vendr median negotiated deal $98,145/yr; pricing typically $40–$120/host/month depending on bundle, with volume bands at 500/1,000/1,000+ hosts.' },
    ecosystem: ['commercial'], dsoStages: ['build','pre-release','operate'] },

  { id: 'aws-ecr-scan', vendor: 'AWS', name: 'Amazon ECR Image Scanning (Enhanced)',
    capabilities: ['container-scan'],
    cost: { model: 'consumption', unit: 0.09, units: 12000, annual: 1080, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/ecr/pricing/',
            contact: 'Cloud account team',
            note: 'Enhanced scanning $0.09/image-scan via Inspector integration. ~1,000 scans/month assumption.' },
    ecosystem: ['aws-native'], dsoStages: ['build','pre-release'] },

  { id: 'azure-defender-containers', vendor: 'Microsoft', name: 'Microsoft Defender for Containers',
    capabilities: ['container-scan','runtime-detect'],
    cost: { model: 'consumption', unit: 84, units: 100, annual: 8400, source: 'estimate',
            sourceUrl: 'https://azure.microsoft.com/en-us/pricing/details/defender-for-cloud/',
            contact: 'Vendor sales',
            note: 'Near $7/vCore/month annualized to $84/vCore/year. Editable units = vCore count (default 100).' },
    ecosystem: ['azure-native'], dsoStages: ['build','operate'] },

  { id: 'checkov', vendor: 'Bridgecrew / Prisma', name: 'Checkov (OSS)',
    capabilities: ['iac-scan'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.checkov.io/',
            contact: 'AppSec lead',
            note: 'OSS IaC scanner: Terraform, CloudFormation, Kubernetes, Docker, Helm.' },
    ecosystem: ['open-source'], dsoStages: ['build','pre-release','deploy'],
    ci: { github: { stage: 'build',
      step: { name: 'Checkov IaC scan', uses: 'bridgecrewio/checkov-action@master',
              with: { directory: '.', quiet: 'true', framework: 'all' } } } } },

  { id: 'kics', vendor: 'Checkmarx', name: 'KICS (OSS)',
    capabilities: ['iac-scan'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://kics.io/',
            contact: 'AppSec lead',
            note: 'OSS IaC scanner. OPA Rego rule engine, Terraform/CloudFormation/Kubernetes/Ansible/Docker.' },
    ecosystem: ['open-source'], dsoStages: ['build','pre-release'],
    ci: { github: { stage: 'build',
      step: { name: 'KICS IaC scan', uses: 'checkmarx/kics-github-action@master',
              with: { path: '.', fail_on: 'high' } } } } },

  { id: 'kube-bench', vendor: 'Aqua', name: 'kube-bench (CIS Kubernetes)',
    capabilities: ['cspm'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/aquasecurity/kube-bench',
            contact: 'Cloud account team',
            note: 'OSS CIS Kubernetes Benchmark checker for running clusters.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['operate'] },

  { id: 'jenkins-hardened', vendor: 'Jenkins', name: 'Pipeline-as-Code (Jenkins, hardened)',
    capabilities: ['pipeline-security'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.jenkins.io/doc/book/security/',
            contact: 'DevOps lead',
            note: 'OSS. Hardening guidance from project: pipeline-as-code, RBAC, agent isolation, credentials provider.' },
    ecosystem: ['open-source'], dsoStages: ['build','deploy'] },

  { id: 'github-actions-hardening', vendor: 'GitHub', name: 'GitHub Actions (hardened)',
    capabilities: ['pipeline-security'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions',
            contact: 'DevOps lead',
            note: 'Process control: pinned action SHAs, OIDC to cloud, environments + required reviewers.' },
    ecosystem: ['open-source'], dsoStages: ['build','deploy'] },

    { id: 'owasp-zap', vendor: 'OWASP', name: 'OWASP ZAP',
    capabilities: ['dast'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.zaproxy.org/',
            contact: 'AppSec lead',
            note: 'OSS DAST. Baseline / full / API scan modes. Operationally heavier than Burp Enterprise.' },
    ecosystem: ['open-source'], dsoStages: ['test','pre-release'],
    ci: { github: { stage: 'dynamic',
      step: { name: 'ZAP baseline scan', uses: 'zaproxy/action-baseline@v0.10.0',
              with: { target: 'https://example.com', cmd_options: '-a' } } } } },

  { id: 'burp-enterprise', vendor: 'PortSwigger', name: 'Burp Suite Enterprise',
    capabilities: ['dast'],
    cost: { model: 'fixed', unit: 8395, units: 1, annual: 8395, source: 'estimate',
            sourceUrl: 'https://portswigger.net/burp/enterprise/pricing',
            contact: 'Vendor sales',
            note: 'Starter tier near $8,395/yr (5 concurrent scans).' },
    ecosystem: ['commercial'], dsoStages: ['test','pre-release'] },

  { id: 'stackhawk', vendor: 'StackHawk', name: 'StackHawk (DAST)',
    capabilities: ['dast'],
    cost: { model: 'fixed', unit: 5988, units: 1, annual: 5988, source: 'estimate',
            sourceUrl: 'https://www.stackhawk.com/pricing/',
            contact: 'Vendor sales',
            note: 'Pro tier near $499/app/month. Developer-friendly DAST built on ZAP engine.' },
    ecosystem: ['commercial'], dsoStages: ['test','pre-release'] },

  { id: 'opa-gatekeeper', vendor: 'OPA / CNCF', name: 'Open Policy Agent + Gatekeeper',
    capabilities: ['policy-as-code'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.openpolicyagent.org/',
            contact: 'Cloud account team',
            note: 'OSS general-purpose policy engine. Gatekeeper is the Kubernetes admission controller.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['deploy','operate'] },

  { id: 'kyverno', vendor: 'Nirmata / CNCF', name: 'Kyverno',
    capabilities: ['policy-as-code'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://kyverno.io/',
            contact: 'Cloud account team',
            note: 'OSS Kubernetes-native policy engine. YAML-only, no separate language.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['deploy','operate'] },

  { id: 'cloud-custodian', vendor: 'CNCF', name: 'Cloud Custodian',
    capabilities: ['policy-as-code','cspm'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://cloudcustodian.io/',
            contact: 'Cloud account team',
            note: 'OSS rules-engine for cloud configuration auto-remediation. AWS / Azure / GCP.' },
    ecosystem: ['open-source'], dsoStages: ['operate'] },

  { id: 'aws-config-rules', vendor: 'AWS', name: 'AWS Config + Conformance Packs',
    capabilities: ['policy-as-code','cspm'],
    cost: { model: 'consumption', unit: 0.003, units: 4000000, annual: 12000, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/config/pricing/',
            contact: 'Cloud account team',
            note: '$0.003 per config item recorded + rule evaluation costs. Highly footprint-dependent.' },
    ecosystem: ['aws-native'], dsoStages: ['operate'] },

  { id: 'vault-oss', vendor: 'HashiCorp', name: 'Vault (OSS)',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.vaultproject.io/',
            contact: 'Cloud account team',
            note: 'OSS self-managed secrets engine. Operationally heavy but no license cost.' },
    ecosystem: ['open-source'], dsoStages: ['deploy','operate'] },

  { id: 'vault-hcp', vendor: 'HashiCorp', name: 'HCP Vault (managed)',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'fixed', unit: 6000, units: 1, annual: 6000, source: 'estimate',
            sourceUrl: 'https://www.hashicorp.com/products/vault/pricing',
            contact: 'Vendor sales',
            note: 'HCP Vault Standard cluster near $0.50/hr. Multi-cloud value if not all-AWS.' },
    ecosystem: ['commercial'], dsoStages: ['deploy','operate'] },

  { id: 'aws-secrets-manager', vendor: 'AWS', name: 'AWS Secrets Manager',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'fixed', unit: 240, units: 1, annual: 240, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/secrets-manager/pricing/',
            contact: 'Cloud account team',
            note: '$0.40/secret/month + $0.05 per 10k API calls. SMB usage (~50 secrets) lands near $240/yr.' },
    ecosystem: ['aws-native'], dsoStages: ['deploy','operate'] },

  { id: 'azure-key-vault', vendor: 'Microsoft', name: 'Azure Key Vault',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'fixed', unit: 30, units: 1, annual: 30, source: 'estimate',
            sourceUrl: 'https://azure.microsoft.com/en-us/pricing/details/key-vault/',
            contact: 'Cloud account team',
            note: '$0.03 per 10k operations. ~$30/yr at SMB usage; HSM-backed keys are extra.' },
    ecosystem: ['azure-native'], dsoStages: ['deploy','operate'] },

  { id: 'gcp-secret-manager', vendor: 'Google Cloud', name: 'Google Secret Manager',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'fixed', unit: 36, units: 1, annual: 36, source: 'estimate',
            sourceUrl: 'https://cloud.google.com/secret-manager/pricing',
            contact: 'Cloud account team',
            note: '$0.06/active-secret-version/month + $0.03 per 10k access ops. SMB usage (~50 secrets) lands near $36/yr.' },
    ecosystem: ['gcp-native'], dsoStages: ['deploy','operate'] },

  { id: 'sealed-secrets', vendor: 'Bitnami', name: 'Sealed Secrets',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/bitnami-labs/sealed-secrets',
            contact: 'Cloud account team',
            note: 'OSS. Encrypts Kubernetes Secrets so they can be checked into git.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['deploy','operate'] },

  { id: 'external-secrets-operator', vendor: 'CNCF', name: 'External Secrets Operator',
    capabilities: ['secrets-mgmt'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://external-secrets.io/',
            contact: 'Cloud account team',
            note: 'OSS. Syncs cloud secret managers into Kubernetes Secrets.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['deploy','operate'] },

  { id: 'third-party-pentest', vendor: 'Third party', name: 'Annual external pentest',
    capabilities: ['pentest','reporting'],
    cost: { model: 'fixed', unit: 18000, units: 1, annual: 18000, source: 'estimate',
            sourceUrl: 'https://deepstrike.io/blog/penetration-testing-cost',
            contact: 'Pentest firm',
            note: 'DeepStrike public pricing guide: SOC 2 SaaS pentest typically $8k–$25k for web app + API + cloud infra scope. $12k–$20k common for first-time SaaS audits. Hourly rates $175–$350/hr for credentialed pentesters. $18k midpoint here.' },
    extraSources: [
      { label: 'BSG pentest pricing guide', url: 'https://bsg.tech/blog/what-can-you-expect-to-pay-for-penetration-testing/' },
      { label: 'Securitywall SOC 2 pentest cost', url: 'https://securitywall.co/blog/soc-2-penetration-testing-cost-what-to-budget-and-what-affects-pricing' },
    ],
    ecosystem: ['commercial'],
    notes: 'SOC 2 audits typically require an annual pentest. Cost varies with scope (number of apps, APIs, cloud accounts) and report format.' },

    { id: 'tenable-io', vendor: 'Tenable', name: 'Tenable Vulnerability Management',
    capabilities: ['vm-endpoint','vm-cloud','reporting'],
    cost: { model: 'fixed', unit: 3700, units: 1, annual: 3700, source: 'estimate',
            sourceUrl: 'https://www.tenable.com/buy',
            contact: 'Vendor sales',
            note: 'tenable.com/buy: $3,700/yr 1-year for 100+ assets ($6,825/2yr or $9,975/3yr). Web App Scanning $6,790/yr extra for 5+ FQDNs. Larger deployments scale up; Vendr median across all customers $18,773/yr.' },
    extraSources: [
      { label: 'Vendr aggregate', url: 'https://www.vendr.com/marketplace/tenable' },
    ],
    ecosystem: ['commercial'] },

  { id: 'nessus-pro', vendor: 'Tenable', name: 'Nessus Professional',
    capabilities: ['vm-endpoint','reporting'],
    cost: { model: 'per-scanner', unit: 4790, units: 1, annual: 4790, source: 'estimate',
            sourceUrl: 'https://www.tenable.com/buy',
            contact: 'Vendor sales',
            note: 'tenable.com/buy: $4,790/yr 1-year per scanner ($9,330.95/2yr; $13,637.54/3yr). Nessus Expert with web-app + external scanning is $6,790/yr.' },
    ecosystem: ['commercial'] },

  { id: 'qualys-vmdr', vendor: 'Qualys', name: 'VMDR',
    capabilities: ['vm-endpoint','vm-cloud','patch-mgmt','reporting'],
    cost: { model: 'fixed', unit: 36062, units: 1, annual: 36062, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/qualys',
            contact: 'Vendor sales',
            note: 'Qualys does not publish list pricing. Vendr median across 98 deals: $36,062/yr (range $3,761–$126,487, avg savings 13%). Per-asset pricing not disclosed publicly.' },
    ecosystem: ['commercial'] },

  { id: 'rapid7-insightvm', vendor: 'Rapid7', name: 'InsightVM',
    capabilities: ['vm-endpoint','vm-cloud','reporting'],
    cost: { model: 'fixed', unit: 29888, units: 1, annual: 29888, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/rapid7',
            contact: 'Vendor sales',
            note: 'Rapid7 does not publish InsightVM pricing on their site. Vendr median across all Rapid7 deals: $29,888/yr (range $6,990–$216,853). Per-asset rates decrease with volume.' },
    ecosystem: ['commercial'] },

  { id: 'aws-inspector', vendor: 'AWS', name: 'Amazon Inspector',
    capabilities: ['vm-cloud','container-scan'],
    cost: { model: 'per-instance', unit: 15.12, units: 50, annual: 756, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/inspector/pricing/',
            contact: 'Cloud account team',
            note: 'EC2 scanning ~$1.258/instance/month annualized to $15.12/instance/year. ECR image scans extra.' },
    ecosystem: ['aws-native'], dsoStages: ['operate'] },

  { id: 'azure-defender-servers', vendor: 'Microsoft', name: 'Defender for Cloud (Servers P2)',
    capabilities: ['vm-cloud','cspm','cnapp'],
    cost: { model: 'per-instance', unit: 180, units: 50, annual: 9000, source: 'estimate',
            sourceUrl: 'https://azure.microsoft.com/en-us/pricing/details/defender-for-cloud/',
            contact: 'Vendor sales',
            note: 'Servers P2 near $15/server/month annualized to $180/server/year. Multi-cloud (AWS/GCP supported).' },
    ecosystem: ['azure-native'] },

  { id: 'gcp-scc-premium', vendor: 'Google Cloud', name: 'Security Command Center Premium',
    capabilities: ['vm-cloud','cspm','container-scan','cnapp'],
    cost: { model: 'consumption', unit: 0.0025, units: 6000000, annual: 15000, source: 'estimate',
            sourceUrl: 'https://cloud.google.com/security-command-center/pricing',
            contact: 'Vendor sales',
            note: 'Premium tier priced as % of GCP spend (~5%). Highly footprint-dependent.' },
    ecosystem: ['gcp-native'] },

  { id: 'mdm-intune', vendor: 'Microsoft', name: 'Intune',
    capabilities: ['patch-mgmt'],
    cost: { model: 'per-user', unit: 96, units: 100, annual: 9600, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/microsoft-intune-pricing',
            contact: 'Vendor sales',
            note: 'Standalone near $8/user/month. Often bundled in M365 E3/E5.' },
    ecosystem: ['azure-native'] },

  { id: 'jamf', vendor: 'Jamf', name: 'Jamf Pro (Apple device mgmt)',
    capabilities: ['patch-mgmt'],
    cost: { model: 'per-endpoint', unit: 150, units: 100, annual: 15000, source: 'estimate',
            sourceUrl: 'https://www.jamf.com/pricing/',
            contact: 'Vendor sales',
            note: 'Jamf pricing page: Jamf for Mac $12.50/device/month ($150/yr, full Business Plan with Pro + Protect + Connect). Mobile $5.75/month, Small Business $4/month. 2–3 year terms typically save 10–20%.' },
    ecosystem: ['commercial'] },

    { id: 'crowdstrike-falcon', vendor: 'CrowdStrike', name: 'Falcon Pro (EDR)',
    capabilities: ['edr'],
    cost: { model: 'per-endpoint', unit: 99.99, units: 100, annual: 9999, source: 'estimate',
            sourceUrl: 'https://www.crowdstrike.com/en-us/pricing/',
            contact: 'Vendor sales',
            note: 'crowdstrike.com pricing: Falcon Go $59.99/device/yr (NGAV only); Falcon Pro $99.99/device/yr (NGAV + EDR + threat intel); Falcon Enterprise $184.99/device/yr (adds Insight XDR, identity, OverWatch). Pro is the typical EDR purchase.' },
    ecosystem: ['commercial'] },

  { id: 'sentinelone', vendor: 'SentinelOne', name: 'Singularity Complete (EDR)',
    capabilities: ['edr'],
    cost: { model: 'per-endpoint', unit: 179.99, units: 100, annual: 17999, source: 'estimate',
            sourceUrl: 'https://www.sentinelone.com/pricing/',
            contact: 'Vendor sales',
            note: 'sentinelone.com pricing: Singularity Core $69.99/yr (NGAV), Control $79.99/yr, Complete $179.99/yr (the full EDR bundle), Commercial $229.99/yr. Enterprise tier is quote-based.' },
    ecosystem: ['commercial'] },

  { id: 'mde-p2', vendor: 'Microsoft', name: 'Defender for Endpoint P2',
    capabilities: ['edr','vm-endpoint'],
    cost: { model: 'per-user', unit: 62.4, units: 100, annual: 6240, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/endpoint-security/microsoft-defender-endpoint',
            contact: 'Vendor sales',
            note: 'Microsoft does not list a standalone P2 dollar price; P2 is included in Microsoft 365 E5 or available as an add-on. Multiple licensing partners cite ~$5.20/user/month standalone. Includes Defender Vulnerability Management.' },
    ecosystem: ['azure-native'] },

  { id: 'cortex-xdr', vendor: 'Palo Alto', name: 'Cortex XDR Pro',
    capabilities: ['edr','reporting'],
    cost: { model: 'fixed', unit: 40501, units: 1, annual: 40501, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/palo-alto-networks',
            contact: 'Vendor sales',
            note: 'Palo Alto does not publish Cortex XDR list pricing. Vendr median across all Palo Alto deals: $40,501/yr (range $9,731–$293,952). Cortex XDR is per-endpoint annual; itprice.com lists Cortex XDR Pro near $81/endpoint/yr but the vendor docs page no longer shows dollars.' },
    ecosystem: ['commercial'] },

  { id: 'falco', vendor: 'CNCF', name: 'Falco',
    capabilities: ['runtime-detect'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://falco.org/',
            contact: 'Cloud account team',
            note: 'OSS eBPF/syscall runtime detection for containers and hosts.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['operate'] },

  { id: 'tetragon', vendor: 'Isovalent / Cilium', name: 'Tetragon',
    capabilities: ['runtime-detect'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://tetragon.io/',
            contact: 'Cloud account team',
            note: 'OSS eBPF runtime security and observability from the Cilium project.' },
    ecosystem: ['open-source','kubernetes-native'], dsoStages: ['operate'] },

  { id: 'splunk-cloud', vendor: 'Splunk', name: 'Splunk Enterprise / Cloud',
    capabilities: ['siem'],
    cost: { model: 'fixed', unit: 74940, units: 1, annual: 74940, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/splunk',
            contact: 'Vendor sales',
            note: 'Splunk does not publish list pricing. Vendr median negotiated contract $74,940 across 142 purchases. UnderDefense lists $1,800–$18,000/yr for 1–10 GB/day footprints; SMB at 50–100 GB/day commonly lands $50k–$150k/yr.' },
    ecosystem: ['commercial'] },

  { id: 'elastic-stack', vendor: 'Elastic', name: 'Elastic Stack (ELK, self-hosted)',
    capabilities: ['siem'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.elastic.co/elastic-stack',
            contact: 'Vendor sales',
            note: 'OSS log/observability/SIEM stack. Heavy ops; license cost is zero, infra cost is not.' },
    ecosystem: ['open-source'] },

  { id: 'elastic-cloud-siem', vendor: 'Elastic', name: 'Elastic Cloud + Security',
    capabilities: ['siem'],
    cost: { model: 'fixed', unit: 24000, units: 1, annual: 24000, source: 'estimate',
            sourceUrl: 'https://www.elastic.co/pricing/',
            contact: 'Vendor sales',
            note: 'Hosted Elastic with Security tier near $2,000/month at SMB scale.' },
    ecosystem: ['commercial'] },

  { id: 'sumologic-cloudsiem', vendor: 'Sumo Logic', name: 'Sumo Logic Cloud SIEM',
    capabilities: ['siem'],
    cost: { model: 'fixed', unit: 36000, units: 1, annual: 36000, source: 'estimate',
            sourceUrl: 'https://www.sumologic.com/pricing/',
            contact: 'Vendor sales',
            note: 'Quote-based ingest pricing. Directional $30k–$60k/yr at SMB scale.' },
    ecosystem: ['commercial'] },

  { id: 'datadog-cloud-siem', vendor: 'Datadog', name: 'Datadog Cloud SIEM',
    capabilities: ['siem','runtime-detect'],
    cost: { model: 'consumption', unit: 0.10, units: 100000, annual: 10000, source: 'estimate',
            sourceUrl: 'https://www.datadoghq.com/pricing/',
            contact: 'Vendor sales',
            note: 'Cloud SIEM starting at $0.10/GB ingested or scanned. ~100GB/month assumption.' },
    ecosystem: ['commercial'] },

  { id: 'aws-guardduty', vendor: 'AWS', name: 'Amazon GuardDuty',
    capabilities: ['runtime-detect'],
    cost: { model: 'fixed', unit: 1500, units: 1, annual: 1500, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/guardduty/pricing/',
            contact: 'Cloud account team',
            note: 'Usage-priced (CloudTrail event volume + flow logs). SMB footprint typically $1k–$3k/yr; midpoint $1,500.' },
    ecosystem: ['aws-native'], dsoStages: ['operate'] },

  { id: 'aws-security-hub', vendor: 'AWS', name: 'AWS Security Hub',
    capabilities: ['cspm','reporting'],
    cost: { model: 'per-instance', unit: 45, units: 100, annual: 4500, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/security-hub/pricing/',
            contact: 'Cloud account team',
            note: 'Essentials plan: $3.75 per resource/month ($45/resource/year). 1 EC2, 12 Lambdas, 18 ECR images, or 125 IAM users/roles each count as one resource. Threat Analytics add-on extra.' },
    ecosystem: ['aws-native'] },

  { id: 'azure-sentinel', vendor: 'Microsoft', name: 'Microsoft Sentinel',
    capabilities: ['siem'],
    cost: { model: 'consumption', unit: 4.30, units: 3000, annual: 12900, source: 'estimate',
            sourceUrl: 'https://azure.microsoft.com/en-us/pricing/details/microsoft-sentinel/',
            contact: 'Vendor sales',
            note: 'Pay-as-you-go ~$4.30/GB ingested. ~250GB/month assumption.' },
    ecosystem: ['azure-native'] },

  { id: 'gcp-chronicle', vendor: 'Google Cloud', name: 'Chronicle SIEM',
    capabilities: ['siem'],
    cost: { model: 'fixed', unit: 50000, units: 1, annual: 50000, source: 'estimate',
            sourceUrl: 'https://docs.cloud.google.com/chronicle/docs/onboard/understand-billing',
            contact: 'Vendor sales',
            note: 'Per-employee fee, unlimited ingest. Google billing docs describe the model; concrete dollar amounts are quote-based. Public ESG modeling cited ~$2.9M/yr for 125k-employee deployments. SMB midpoint ~$50k/yr per peerspot.com.' },
    ecosystem: ['gcp-native'] },

  { id: 'prowler', vendor: 'Prowler', name: 'Prowler (OSS CSPM)',
    capabilities: ['cspm'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/prowler-cloud/prowler',
            contact: 'Cloud account team',
            note: 'OSS multi-cloud posture scanner: AWS, Azure, GCP, Kubernetes.' },
    ecosystem: ['open-source'],
    ci: { github: { stage: 'deploy',
      step: { name: 'Prowler CSPM scan', run: 'pipx run prowler aws --quick-inventory' } } } },

  { id: 'scoutsuite', vendor: 'NCC Group', name: 'ScoutSuite',
    capabilities: ['cspm'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://github.com/nccgroup/ScoutSuite',
            contact: 'Cloud account team',
            note: 'OSS multi-cloud auditing tool.' },
    ecosystem: ['open-source'] },

  { id: 'wiz', vendor: 'Wiz', name: 'Wiz CNAPP',
    capabilities: ['cnapp','cspm','container-scan','vm-cloud'],
    cost: { model: 'fixed', unit: 149319, units: 1, annual: 149319, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/wiz',
            contact: 'Vendor sales',
            note: 'Wiz does not publish list pricing. Vendr median negotiated deal $149,319/yr; deals range $50k–$200k+ depending on workload count. Per-workload effective rate ~$10–$30/yr.' },
    ecosystem: ['commercial'] },

  { id: 'orca', vendor: 'Orca Security', name: 'Orca Security CNAPP',
    capabilities: ['cnapp','cspm','container-scan','vm-cloud'],
    cost: { model: 'fixed', unit: 99901, units: 1, annual: 99901, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/orca-security',
            contact: 'Vendor sales',
            note: 'Orca does not publish list pricing. Vendr median negotiated deal $99,901/yr; SMB workload-based pricing typically $60k–$120k/yr with volume discounts at higher tiers.' },
    ecosystem: ['commercial'] },

  { id: 'prisma-cloud', vendor: 'Palo Alto', name: 'Prisma Cloud',
    capabilities: ['cnapp','cspm','container-scan','vm-cloud','iac-scan'],
    cost: { model: 'fixed', unit: 18000, units: 1, annual: 18000, source: 'estimate',
            sourceUrl: 'https://www.paloaltonetworks.com/resources/guides/prisma-cloud-enterprise-edition-licensing-guide',
            contact: 'Vendor sales',
            note: 'Palo Alto licensing guide: 100 credits = $9,000/yr Business Edition or $18,000/yr Enterprise Edition. Estimate uses Enterprise Edition baseline; large deployments scale into six figures.' },
    ecosystem: ['commercial'] },

  { id: 'modsec-crs', vendor: 'OWASP', name: 'ModSecurity + OWASP CRS (self-hosted)',
    capabilities: ['waf'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://coreruleset.org/',
            contact: 'Cloud account team',
            note: 'OSS WAF engine + rule set. Self-hosted in front of NGINX/Apache.' },
    ecosystem: ['open-source'] },

  { id: 'aws-waf', vendor: 'AWS', name: 'AWS WAF',
    capabilities: ['waf'],
    cost: { model: 'fixed', unit: 1200, units: 1, annual: 1200, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/waf/pricing/',
            contact: 'Cloud account team',
            note: '$5 per web ACL/month + $1/rule + $0.60 per 1M requests. SMB footprint ~$100/month → $1,200/yr.' },
    ecosystem: ['aws-native'] },

  { id: 'azure-front-door-waf', vendor: 'Microsoft', name: 'Azure Front Door + WAF',
    capabilities: ['waf'],
    cost: { model: 'fixed', unit: 1980, units: 1, annual: 1980, source: 'estimate',
            sourceUrl: 'https://azure.microsoft.com/en-us/pricing/details/frontdoor/',
            contact: 'Cloud account team',
            note: 'Standard tier near $35/month base + $0.022 per rule eval. SMB footprint ~$165/month → $1,980/yr.' },
    ecosystem: ['azure-native'] },

  { id: 'cloudflare-waf', vendor: 'Cloudflare', name: 'Cloudflare WAF (Pro/Business)',
    capabilities: ['waf'],
    cost: { model: 'fixed', unit: 2400, units: 1, annual: 2400, source: 'estimate',
            sourceUrl: 'https://www.cloudflare.com/plans/',
            contact: 'Vendor sales',
            note: 'Business plan near $200/month per zone. Pro is $20/month.' },
    ecosystem: ['commercial'] },

    { id: 'okta-workforce', vendor: 'Okta', name: 'Okta Workforce Identity',
    capabilities: ['iam'],
    cost: { model: 'per-user', unit: 72, units: 100, annual: 7200, source: 'estimate',
            sourceUrl: 'https://www.okta.com/pricing/',
            contact: 'Vendor sales',
            note: 'SSO + Adaptive MFA bundle near $6/user/month. Lifecycle/governance modules add cost.' },
    ecosystem: ['commercial'] },

  { id: 'entra-id-p1', vendor: 'Microsoft', name: 'Entra ID P1',
    capabilities: ['iam'],
    cost: { model: 'per-user', unit: 72, units: 100, annual: 7200, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/microsoft-entra-pricing',
            contact: 'Vendor sales',
            note: 'P1 near $6/user/month. Often bundled in M365 E3.' },
    ecosystem: ['azure-native'] },

  { id: 'entra-id-p2', vendor: 'Microsoft', name: 'Entra ID P2',
    capabilities: ['iam'],
    cost: { model: 'per-user', unit: 108, units: 100, annual: 10800, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/microsoft-entra-pricing',
            contact: 'Vendor sales',
            note: 'P2 near $9/user/month. Adds Identity Protection + Privileged Identity Management.' },
    ecosystem: ['azure-native'] },

  { id: 'jumpcloud', vendor: 'JumpCloud', name: 'JumpCloud Directory Platform',
    capabilities: ['iam','patch-mgmt'],
    cost: { model: 'per-user', unit: 276, units: 100, annual: 27600, source: 'estimate',
            sourceUrl: 'https://jumpcloud.com/pricing',
            contact: 'Vendor sales',
            note: 'A la carte (annual billing): SSO $11/user/mo + MFA $3/user/mo + Device Management $9/user/mo = $23/user/mo ($276/yr). Platform bundles available via sales.' },
    ecosystem: ['commercial'] },

  { id: 'auth0', vendor: 'Okta', name: 'Auth0 (B2C/B2B)',
    capabilities: ['iam'],
    cost: { model: 'fixed', unit: 2880, units: 1, annual: 2880, source: 'estimate',
            sourceUrl: 'https://auth0.com/pricing',
            contact: 'Vendor sales',
            note: 'Essentials starts near $240/month for 1k MAUs. Customer-facing apps; not workforce IAM.' },
    ecosystem: ['commercial'] },

  { id: 'keycloak', vendor: 'Red Hat', name: 'Keycloak (OSS)',
    capabilities: ['iam'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.keycloak.org/',
            contact: 'AppSec lead',
            note: 'OSS identity provider. SAML, OIDC, social login.' },
    ecosystem: ['open-source'] },

  { id: 'istio', vendor: 'CNCF', name: 'Istio',
    capabilities: ['service-mesh'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://istio.io/',
            contact: 'Cloud account team',
            note: 'OSS service mesh, mTLS, traffic policy, observability for Kubernetes.' },
    ecosystem: ['open-source','kubernetes-native'] },

  { id: 'linkerd', vendor: 'Buoyant / CNCF', name: 'Linkerd',
    capabilities: ['service-mesh'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://linkerd.io/',
            contact: 'Cloud account team',
            note: 'OSS lightweight service mesh. Simpler than Istio.' },
    ecosystem: ['open-source','kubernetes-native'] },

  { id: 'cilium', vendor: 'Isovalent / CNCF', name: 'Cilium (eBPF networking)',
    capabilities: ['service-mesh','runtime-detect'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://cilium.io/',
            contact: 'Cloud account team',
            note: 'OSS eBPF-based CNI with network policy + service mesh capabilities.' },
    ecosystem: ['open-source','kubernetes-native'] },

  { id: 'mde-o365-p2', vendor: 'Microsoft', name: 'Defender for Office 365 P2',
    capabilities: ['email-sec'],
    cost: { model: 'per-user', unit: 60, units: 100, annual: 6000, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/threat-protection/office-365-defender',
            contact: 'Vendor sales',
            note: 'List near $5/user/month for P2. Often bundled in M365 E5.' },
    ecosystem: ['azure-native'] },

  { id: 'proofpoint-email', vendor: 'Proofpoint', name: 'Email Protection',
    capabilities: ['email-sec'],
    cost: { model: 'per-user', unit: 36, units: 100, annual: 3600, source: 'estimate',
            sourceUrl: 'https://costbench.com/software/email-security/proofpoint/',
            contact: 'Vendor sales',
            note: 'Proofpoint Essentials Business $3.03/user/month = $36/yr per costbench.com aggregate. Range across plans $2–$15/user/month; enterprise tiers add TAP / DLP / archiving.' },
    ecosystem: ['commercial'] },

  { id: 'mimecast', vendor: 'Mimecast', name: 'Mimecast Email Security',
    capabilities: ['email-sec'],
    cost: { model: 'per-user', unit: 60, units: 100, annual: 6000, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/mimecast',
            contact: 'Vendor sales',
            note: 'Mimecast does not publish list pricing. Vendr / costbench aggregates: $5–$15/user/month depending on tier; ~$3/user/month achievable at 500+ users with 3-yr commit. $5/user/month midpoint = $60/yr.' },
    ecosystem: ['commercial'] },

  { id: 'netskope', vendor: 'Netskope', name: 'Netskope SSE (CASB+SWG+DLP)',
    capabilities: ['dlp'],
    cost: { model: 'per-user', unit: 360, units: 100, annual: 36000, source: 'estimate',
            sourceUrl: 'https://www.vendr.com/marketplace/netskope',
            contact: 'Vendor sales',
            note: 'Netskope does not publish list pricing. Vendr aggregates: CASB-only $15–$35/user/mo, SWG $20–$45, ZTNA $25–$50, full SASE bundle $40–$75. SSE stack (CASB+SWG+DLP) midpoint ~$30/user/mo = $360/yr.' },
    ecosystem: ['commercial'] },

  { id: 'mdca', vendor: 'Microsoft', name: 'Defender for Cloud Apps (CASB)',
    capabilities: ['dlp'],
    cost: { model: 'per-user', unit: 60, units: 100, annual: 6000, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/siem-and-xdr/microsoft-defender-cloud-apps',
            contact: 'Vendor sales',
            note: 'List near $5/user/month. Bundled in M365 E5 Compliance.' },
    ecosystem: ['azure-native'] },

  { id: 'openvas', vendor: 'Greenbone', name: 'OpenVAS / Greenbone Community',
    capabilities: ['vm-endpoint','vm-cloud'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.openvas.org/',
            contact: '',
            note: 'OSS network vulnerability scanner. Greenbone Community Edition is the free distribution.' },
    ecosystem: ['open-source'] },

  { id: 'defectdojo', vendor: 'OWASP', name: 'DefectDojo',
    capabilities: ['reporting'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://www.defectdojo.org/',
            contact: '',
            note: 'OSS application vulnerability management and audit-evidence dashboard. Imports findings from most scanners (ZAP, Trivy, Snyk, Burp, Semgrep, etc.).' },
    ecosystem: ['open-source'] },

  { id: 'wazuh', vendor: 'Wazuh', name: 'Wazuh (XDR + SIEM)',
    capabilities: ['edr','siem'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://wazuh.com/',
            contact: '',
            note: 'OSS host-based detection, log analysis, file integrity monitoring, and SIEM. Self-hosted. Commercial Wazuh Cloud and support tiers available.' },
    ecosystem: ['open-source'] },

  { id: 'aws-audit-manager', vendor: 'AWS', name: 'AWS Audit Manager',
    capabilities: ['reporting'],
    cost: { model: 'fixed', unit: 500, units: 1, annual: 500, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/audit-manager/pricing/',
            contact: 'Vendor sales',
            note: '$1.25 per 1,000 resource assessments. SMB usage typically lands $200–$1,000/yr; midpoint $500. Free tier: 35,000 assessments/month for first 2 months.' },
    ecosystem: ['aws-native'] },

  { id: 'aws-ssm-patch-manager', vendor: 'AWS', name: 'Systems Manager Patch Manager',
    capabilities: ['patch-mgmt'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager.html',
            contact: '',
            note: 'No additional charge for managed EC2 / on-prem (Advanced Tier) instances. Hybrid Activations bill at standard SSM rates if outside the included quota.' },
    ecosystem: ['aws-native'] },

  { id: 'aws-macie', vendor: 'AWS', name: 'Amazon Macie',
    capabilities: ['dlp'],
    cost: { model: 'fixed', unit: 1200, units: 1, annual: 1200, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/macie/pricing/',
            contact: 'Vendor sales',
            note: '$0.10 per S3 bucket/month + $0.01 per 100K objects + $1/GB inspected. SMB at 50 buckets and 100GB profiled lands ~$1,200/yr.' },
    ecosystem: ['aws-native'] },

  { id: 'aws-security-lake', vendor: 'AWS', name: 'AWS Security Lake',
    capabilities: ['siem'],
    cost: { model: 'fixed', unit: 1500, units: 1, annual: 1500, source: 'estimate',
            sourceUrl: 'https://aws.amazon.com/security-lake/pricing/',
            contact: 'Vendor sales',
            note: '$0.75/GB CloudTrail + $0.25/GB other AWS logs + $0.035/GB normalization. SMB at ~50GB CloudTrail + 200GB other = ~$100/month = $1,200/yr (excludes query / S3 storage costs).' },
    ecosystem: ['aws-native'] },

  { id: 'azure-purview-compliance', vendor: 'Microsoft', name: 'Purview Compliance Manager',
    capabilities: ['reporting'],
    cost: { model: 'per-user', unit: 24, units: 100, annual: 2400, source: 'estimate',
            sourceUrl: 'https://www.microsoft.com/en-us/security/business/microsoft-purview',
            contact: 'Vendor sales',
            note: 'Compliance Manager dashboards and audit-evidence are bundled in M365 E5 Compliance and standalone Purview SKUs. Standalone licensing partner aggregates put it ~$2/user/month. Free baseline assessment included with most M365 plans.' },
    ecosystem: ['azure-native'] },

  { id: 'gcp-vm-manager', vendor: 'Google Cloud', name: 'VM Manager OS Patch Management',
    capabilities: ['patch-mgmt'],
    cost: { model: 'free', unit: 0, units: 0, annual: 0, source: 'free',
            sourceUrl: 'https://cloud.google.com/compute/docs/os-patch-management',
            contact: '',
            note: 'OS patch management is included with Compute Engine at no additional charge. Bills only the underlying VM, network, and storage.' },
    ecosystem: ['gcp-native'] },

  { id: 'gcp-cloud-dlp', vendor: 'Google Cloud', name: 'Sensitive Data Protection (Cloud DLP)',
    capabilities: ['dlp'],
    cost: { model: 'fixed', unit: 360, units: 1, annual: 360, source: 'estimate',
            sourceUrl: 'https://cloud.google.com/sensitive-data-protection/pricing',
            contact: 'Vendor sales',
            note: '$1/GB for 1GB–50TB inspection or transformation. Discovery profiling $0.03/GB. SMB at ~30GB inspection lands ~$360/yr.' },
    ecosystem: ['gcp-native'] },

  { id: 'gcp-cloud-armor', vendor: 'Google Cloud', name: 'Cloud Armor (Standard)',
    capabilities: ['waf'],
    cost: { model: 'fixed', unit: 2400, units: 1, annual: 2400, source: 'estimate',
            sourceUrl: 'https://cloud.google.com/armor/pricing',
            contact: 'Vendor sales',
            note: 'Standard tier: $0.273972603/hour per protected resource ($2,400/yr) after a 2-month free trial, plus $0.75 per million global-scope requests ($0.60 regional). SMB at 1 protected resource lands ~$2,400/yr. Enterprise Annual subscription is $36,000/yr (100 resources included).' },
    ecosystem: ['gcp-native'] },
];

window.DEFAULT_SELECTIONS = Object.fromEntries(
  window.CAPABILITIES.map(c => [c.id, 'none'])
);

window.DEFAULT_ENFORCEMENT = Object.fromEntries(
  window.CAPABILITIES.map(c => [c.id, 'none'])
);

window.SCENARIOS = [
  { id: 'foss-native', name: 'FOSS-Native',
    summary: 'Minimum-spend coverage across every capability using free / open-source tools wherever possible. Establishes a baseline budget before considering commercial swaps.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'pre-commit-framework',
      'sast': 'semgrep-oss',
      'sca': 'owasp-dep-check',
      'sbom': 'syft',
      'container-scan': 'trivy',
      'iac-scan': 'checkov',
      'pipeline-security': 'github-actions-hardening',
      'dast': 'owasp-zap',
      'policy-as-code': 'opa-gatekeeper',
      'secrets-mgmt': 'vault-oss',
      'pentest': 'third-party-pentest',
      'vm-endpoint': 'openvas',
      'vm-cloud': 'openvas',
      'reporting': 'defectdojo',
      'edr': 'wazuh',
      'cspm': 'prowler',
      'runtime-detect': 'falco',
      'siem': 'wazuh',
      'waf': 'modsec-crs',
      'iam': 'keycloak',
      'service-mesh': 'linkerd',
    },
    enforcement: {
      'sast': 'visibility', 'dast': 'visibility', 'iac-scan': 'visibility',
      'sbom': 'visibility', 'container-scan': 'visibility', 'sca': 'visibility',
      'precommit-hooks': 'visibility', 'pipeline-security': 'visibility',
      'secrets-mgmt': 'soft', 'policy-as-code': 'visibility',
    } },

  { id: 'aws-native', name: 'AWS-Native',
    summary: 'AWS-native services for every capability they natively cover. Pairs with OSS for AppSec where AWS does not have a first-party tool.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'pre-commit-framework',
      'sast': 'semgrep-oss',
      'sca': 'dependabot',
      'sbom': 'syft',
      'container-scan': 'aws-ecr-scan',
      'iac-scan': 'checkov',
      'pipeline-security': 'github-actions-hardening',
      'dast': 'owasp-zap',
      'policy-as-code': 'aws-config-rules',
      'secrets-mgmt': 'aws-secrets-manager',
      'pentest': 'third-party-pentest',
      'vm-cloud': 'aws-inspector',
      'patch-mgmt': 'aws-ssm-patch-manager',
      'reporting': 'aws-audit-manager',
      'cspm': 'aws-security-hub',
      'runtime-detect': 'aws-guardduty',
      'siem': 'aws-security-lake',
      'dlp': 'aws-macie',
      'waf': 'aws-waf',
      'iam': 'okta-workforce',
    } },

  { id: 'azure-native', name: 'Azure / Microsoft-Native',
    summary: 'Microsoft / Azure stack: Defender for everything, Sentinel SIEM, Entra ID for identity, Key Vault for secrets.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'pre-commit-framework',
      'sast': 'github-advanced-security',
      'sca': 'github-advanced-security',
      'sbom': 'github-advanced-security',
      'container-scan': 'azure-defender-containers',
      'iac-scan': 'checkov',
      'pipeline-security': 'github-actions-hardening',
      'dast': 'owasp-zap',
      'policy-as-code': 'opa-gatekeeper',
      'secrets-mgmt': 'azure-key-vault',
      'pentest': 'third-party-pentest',
      'vm-endpoint': 'mde-p2',
      'vm-cloud': 'azure-defender-servers',
      'cspm': 'azure-defender-servers',
      'edr': 'mde-p2',
      'siem': 'azure-sentinel',
      'runtime-detect': 'azure-defender-containers',
      'waf': 'azure-front-door-waf',
      'iam': 'entra-id-p2',
      'email-sec': 'mde-o365-p2',
      'dlp': 'mdca',
      'patch-mgmt': 'mdm-intune',
      'reporting': 'azure-purview-compliance',
      'cnapp': 'azure-defender-servers',
    } },

  { id: 'gcp-native', name: 'GCP-Native',
    summary: 'Google Cloud stack: Security Command Center for posture + workload, Chronicle for SIEM, Secret Manager.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'pre-commit-framework',
      'sast': 'semgrep-oss',
      'sca': 'dependabot',
      'sbom': 'syft',
      'container-scan': 'trivy',
      'iac-scan': 'checkov',
      'pipeline-security': 'github-actions-hardening',
      'dast': 'owasp-zap',
      'policy-as-code': 'opa-gatekeeper',
      'secrets-mgmt': 'gcp-secret-manager',
      'pentest': 'third-party-pentest',
      'vm-cloud': 'gcp-scc-premium',
      'patch-mgmt': 'gcp-vm-manager',
      'reporting': 'gcp-scc-premium',
      'cspm': 'gcp-scc-premium',
      'cnapp': 'gcp-scc-premium',
      'siem': 'gcp-chronicle',
      'runtime-detect': 'falco',
      'dlp': 'gcp-cloud-dlp',
      'waf': 'gcp-cloud-armor',
      'iam': 'okta-workforce',
    } },

  { id: 'enterprise-commercial', name: 'Enterprise Commercial',
    summary: 'Premium commercial tooling end-to-end. Snyk + Burp + Wiz + CrowdStrike + Splunk + Okta. Highest-cost path with the most managed coverage.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'gitguardian',
      'sast': 'snyk-code',
      'sca': 'snyk-open-source',
      'sbom': 'snyk-open-source',
      'container-scan': 'wiz',
      'iac-scan': 'wiz',
      'pipeline-security': 'github-actions-hardening',
      'dast': 'burp-enterprise',
      'policy-as-code': 'opa-gatekeeper',
      'secrets-mgmt': 'vault-hcp',
      'pentest': 'third-party-pentest',
      'vm-endpoint': 'tenable-io',
      'vm-cloud': 'wiz',
      'cspm': 'wiz',
      'cnapp': 'wiz',
      'edr': 'crowdstrike-falcon',
      'siem': 'splunk-cloud',
      'runtime-detect': 'sysdig-secure',
      'waf': 'cloudflare-waf',
      'iam': 'okta-workforce',
      'email-sec': 'proofpoint-email',
      'dlp': 'netskope',
      'patch-mgmt': 'mdm-intune',
      'reporting': 'defectdojo',
      'service-mesh': 'istio',
    },
    enforcement: {
      'sast': 'soft', 'dast': 'soft', 'iac-scan': 'soft',
      'sbom': 'hard', 'container-scan': 'soft', 'sca': 'soft',
      'precommit-hooks': 'visibility', 'pipeline-security': 'soft',
      'secrets-mgmt': 'hard', 'policy-as-code': 'soft',
    } },

  { id: 'github-native', name: 'GitHub-Native',
    summary: 'GitHub Advanced Security covers SAST, SCA, SBOM, and secret scanning. CODEOWNERS for code review, Actions hardening for pipeline security; OSS for cloud/runtime.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'github-advanced-security',
      'sast': 'github-advanced-security',
      'sca': 'github-advanced-security',
      'sbom': 'github-advanced-security',
      'container-scan': 'trivy',
      'iac-scan': 'trivy',
      'pipeline-security': 'github-actions-hardening',
      'dast': 'owasp-zap',
      'policy-as-code': 'opa-gatekeeper',
      'secrets-mgmt': 'vault-oss',
      'pentest': 'third-party-pentest',
      'vm-cloud': 'openvas',
      'cspm': 'prowler',
      'runtime-detect': 'falco',
      'siem': 'wazuh',
      'edr': 'wazuh',
      'waf': 'modsec-crs',
      'iam': 'keycloak',
      'reporting': 'defectdojo',
    } },

  { id: 'gitlab-native', name: 'GitLab-Native',
    summary: 'GitLab Ultimate bundles SAST, SCA, SBOM, DAST, container scanning, IaC scanning, and pipeline security in one license. OSS for cloud/runtime.',
    selections: {
      'code-review-controls': 'codeowners-native',
      'precommit-hooks': 'pre-commit-framework',
      'sast': 'gitlab-ultimate',
      'sca': 'gitlab-ultimate',
      'sbom': 'gitlab-ultimate',
      'dast': 'gitlab-ultimate',
      'container-scan': 'gitlab-ultimate',
      'iac-scan': 'gitlab-ultimate',
      'pipeline-security': 'gitlab-ultimate',
      'policy-as-code': 'opa-gatekeeper',
      'secrets-mgmt': 'vault-oss',
      'pentest': 'third-party-pentest',
      'vm-cloud': 'openvas',
      'vm-endpoint': 'openvas',
      'cspm': 'prowler',
      'runtime-detect': 'falco',
      'siem': 'wazuh',
      'edr': 'wazuh',
      'waf': 'modsec-crs',
      'iam': 'keycloak',
      'reporting': 'defectdojo',
    } },
];
